
package intswitchbench

import org.openjdk.jmh.annotations.Benchmark
import org.openjdk.jmh.annotations.Scope
import org.openjdk.jmh.annotations.State
import org.openjdk.jmh.annotations.OperationsPerInvocation

object IntMemberData256 {

  sealed trait WithIntMember {
    val selector: Int
  }

  case class NthSelector1(p: Int) extends WithIntMember { val selector = 1 }
  case class NthSelector2(p: Int) extends WithIntMember { val selector = 2 }
  case class NthSelector3(p: Int) extends WithIntMember { val selector = 3 }
  case class NthSelector4(p: Int) extends WithIntMember { val selector = 4 }
  case class NthSelector5(p: Int) extends WithIntMember { val selector = 5 }
  case class NthSelector6(p: Int) extends WithIntMember { val selector = 6 }
  case class NthSelector7(p: Int) extends WithIntMember { val selector = 7 }
  case class NthSelector8(p: Int) extends WithIntMember { val selector = 8 }
  case class NthSelector9(p: Int) extends WithIntMember { val selector = 9 }
  case class NthSelector10(p: Int) extends WithIntMember { val selector = 10 }
  case class NthSelector11(p: Int) extends WithIntMember { val selector = 11 }
  case class NthSelector12(p: Int) extends WithIntMember { val selector = 12 }
  case class NthSelector13(p: Int) extends WithIntMember { val selector = 13 }
  case class NthSelector14(p: Int) extends WithIntMember { val selector = 14 }
  case class NthSelector15(p: Int) extends WithIntMember { val selector = 15 }
  case class NthSelector16(p: Int) extends WithIntMember { val selector = 16 }
  case class NthSelector17(p: Int) extends WithIntMember { val selector = 17 }
  case class NthSelector18(p: Int) extends WithIntMember { val selector = 18 }
  case class NthSelector19(p: Int) extends WithIntMember { val selector = 19 }
  case class NthSelector20(p: Int) extends WithIntMember { val selector = 20 }
  case class NthSelector21(p: Int) extends WithIntMember { val selector = 21 }
  case class NthSelector22(p: Int) extends WithIntMember { val selector = 22 }
  case class NthSelector23(p: Int) extends WithIntMember { val selector = 23 }
  case class NthSelector24(p: Int) extends WithIntMember { val selector = 24 }
  case class NthSelector25(p: Int) extends WithIntMember { val selector = 25 }
  case class NthSelector26(p: Int) extends WithIntMember { val selector = 26 }
  case class NthSelector27(p: Int) extends WithIntMember { val selector = 27 }
  case class NthSelector28(p: Int) extends WithIntMember { val selector = 28 }
  case class NthSelector29(p: Int) extends WithIntMember { val selector = 29 }
  case class NthSelector30(p: Int) extends WithIntMember { val selector = 30 }
  case class NthSelector31(p: Int) extends WithIntMember { val selector = 31 }
  case class NthSelector32(p: Int) extends WithIntMember { val selector = 32 }
  case class NthSelector33(p: Int) extends WithIntMember { val selector = 33 }
  case class NthSelector34(p: Int) extends WithIntMember { val selector = 34 }
  case class NthSelector35(p: Int) extends WithIntMember { val selector = 35 }
  case class NthSelector36(p: Int) extends WithIntMember { val selector = 36 }
  case class NthSelector37(p: Int) extends WithIntMember { val selector = 37 }
  case class NthSelector38(p: Int) extends WithIntMember { val selector = 38 }
  case class NthSelector39(p: Int) extends WithIntMember { val selector = 39 }
  case class NthSelector40(p: Int) extends WithIntMember { val selector = 40 }
  case class NthSelector41(p: Int) extends WithIntMember { val selector = 41 }
  case class NthSelector42(p: Int) extends WithIntMember { val selector = 42 }
  case class NthSelector43(p: Int) extends WithIntMember { val selector = 43 }
  case class NthSelector44(p: Int) extends WithIntMember { val selector = 44 }
  case class NthSelector45(p: Int) extends WithIntMember { val selector = 45 }
  case class NthSelector46(p: Int) extends WithIntMember { val selector = 46 }
  case class NthSelector47(p: Int) extends WithIntMember { val selector = 47 }
  case class NthSelector48(p: Int) extends WithIntMember { val selector = 48 }
  case class NthSelector49(p: Int) extends WithIntMember { val selector = 49 }
  case class NthSelector50(p: Int) extends WithIntMember { val selector = 50 }
  case class NthSelector51(p: Int) extends WithIntMember { val selector = 51 }
  case class NthSelector52(p: Int) extends WithIntMember { val selector = 52 }
  case class NthSelector53(p: Int) extends WithIntMember { val selector = 53 }
  case class NthSelector54(p: Int) extends WithIntMember { val selector = 54 }
  case class NthSelector55(p: Int) extends WithIntMember { val selector = 55 }
  case class NthSelector56(p: Int) extends WithIntMember { val selector = 56 }
  case class NthSelector57(p: Int) extends WithIntMember { val selector = 57 }
  case class NthSelector58(p: Int) extends WithIntMember { val selector = 58 }
  case class NthSelector59(p: Int) extends WithIntMember { val selector = 59 }
  case class NthSelector60(p: Int) extends WithIntMember { val selector = 60 }
  case class NthSelector61(p: Int) extends WithIntMember { val selector = 61 }
  case class NthSelector62(p: Int) extends WithIntMember { val selector = 62 }
  case class NthSelector63(p: Int) extends WithIntMember { val selector = 63 }
  case class NthSelector64(p: Int) extends WithIntMember { val selector = 64 }
  case class NthSelector65(p: Int) extends WithIntMember { val selector = 65 }
  case class NthSelector66(p: Int) extends WithIntMember { val selector = 66 }
  case class NthSelector67(p: Int) extends WithIntMember { val selector = 67 }
  case class NthSelector68(p: Int) extends WithIntMember { val selector = 68 }
  case class NthSelector69(p: Int) extends WithIntMember { val selector = 69 }
  case class NthSelector70(p: Int) extends WithIntMember { val selector = 70 }
  case class NthSelector71(p: Int) extends WithIntMember { val selector = 71 }
  case class NthSelector72(p: Int) extends WithIntMember { val selector = 72 }
  case class NthSelector73(p: Int) extends WithIntMember { val selector = 73 }
  case class NthSelector74(p: Int) extends WithIntMember { val selector = 74 }
  case class NthSelector75(p: Int) extends WithIntMember { val selector = 75 }
  case class NthSelector76(p: Int) extends WithIntMember { val selector = 76 }
  case class NthSelector77(p: Int) extends WithIntMember { val selector = 77 }
  case class NthSelector78(p: Int) extends WithIntMember { val selector = 78 }
  case class NthSelector79(p: Int) extends WithIntMember { val selector = 79 }
  case class NthSelector80(p: Int) extends WithIntMember { val selector = 80 }
  case class NthSelector81(p: Int) extends WithIntMember { val selector = 81 }
  case class NthSelector82(p: Int) extends WithIntMember { val selector = 82 }
  case class NthSelector83(p: Int) extends WithIntMember { val selector = 83 }
  case class NthSelector84(p: Int) extends WithIntMember { val selector = 84 }
  case class NthSelector85(p: Int) extends WithIntMember { val selector = 85 }
  case class NthSelector86(p: Int) extends WithIntMember { val selector = 86 }
  case class NthSelector87(p: Int) extends WithIntMember { val selector = 87 }
  case class NthSelector88(p: Int) extends WithIntMember { val selector = 88 }
  case class NthSelector89(p: Int) extends WithIntMember { val selector = 89 }
  case class NthSelector90(p: Int) extends WithIntMember { val selector = 90 }
  case class NthSelector91(p: Int) extends WithIntMember { val selector = 91 }
  case class NthSelector92(p: Int) extends WithIntMember { val selector = 92 }
  case class NthSelector93(p: Int) extends WithIntMember { val selector = 93 }
  case class NthSelector94(p: Int) extends WithIntMember { val selector = 94 }
  case class NthSelector95(p: Int) extends WithIntMember { val selector = 95 }
  case class NthSelector96(p: Int) extends WithIntMember { val selector = 96 }
  case class NthSelector97(p: Int) extends WithIntMember { val selector = 97 }
  case class NthSelector98(p: Int) extends WithIntMember { val selector = 98 }
  case class NthSelector99(p: Int) extends WithIntMember { val selector = 99 }
  case class NthSelector100(p: Int) extends WithIntMember { val selector = 100 }
  case class NthSelector101(p: Int) extends WithIntMember { val selector = 101 }
  case class NthSelector102(p: Int) extends WithIntMember { val selector = 102 }
  case class NthSelector103(p: Int) extends WithIntMember { val selector = 103 }
  case class NthSelector104(p: Int) extends WithIntMember { val selector = 104 }
  case class NthSelector105(p: Int) extends WithIntMember { val selector = 105 }
  case class NthSelector106(p: Int) extends WithIntMember { val selector = 106 }
  case class NthSelector107(p: Int) extends WithIntMember { val selector = 107 }
  case class NthSelector108(p: Int) extends WithIntMember { val selector = 108 }
  case class NthSelector109(p: Int) extends WithIntMember { val selector = 109 }
  case class NthSelector110(p: Int) extends WithIntMember { val selector = 110 }
  case class NthSelector111(p: Int) extends WithIntMember { val selector = 111 }
  case class NthSelector112(p: Int) extends WithIntMember { val selector = 112 }
  case class NthSelector113(p: Int) extends WithIntMember { val selector = 113 }
  case class NthSelector114(p: Int) extends WithIntMember { val selector = 114 }
  case class NthSelector115(p: Int) extends WithIntMember { val selector = 115 }
  case class NthSelector116(p: Int) extends WithIntMember { val selector = 116 }
  case class NthSelector117(p: Int) extends WithIntMember { val selector = 117 }
  case class NthSelector118(p: Int) extends WithIntMember { val selector = 118 }
  case class NthSelector119(p: Int) extends WithIntMember { val selector = 119 }
  case class NthSelector120(p: Int) extends WithIntMember { val selector = 120 }
  case class NthSelector121(p: Int) extends WithIntMember { val selector = 121 }
  case class NthSelector122(p: Int) extends WithIntMember { val selector = 122 }
  case class NthSelector123(p: Int) extends WithIntMember { val selector = 123 }
  case class NthSelector124(p: Int) extends WithIntMember { val selector = 124 }
  case class NthSelector125(p: Int) extends WithIntMember { val selector = 125 }
  case class NthSelector126(p: Int) extends WithIntMember { val selector = 126 }
  case class NthSelector127(p: Int) extends WithIntMember { val selector = 127 }
  case class NthSelector128(p: Int) extends WithIntMember { val selector = 128 }
  case class NthSelector129(p: Int) extends WithIntMember { val selector = 129 }
  case class NthSelector130(p: Int) extends WithIntMember { val selector = 130 }
  case class NthSelector131(p: Int) extends WithIntMember { val selector = 131 }
  case class NthSelector132(p: Int) extends WithIntMember { val selector = 132 }
  case class NthSelector133(p: Int) extends WithIntMember { val selector = 133 }
  case class NthSelector134(p: Int) extends WithIntMember { val selector = 134 }
  case class NthSelector135(p: Int) extends WithIntMember { val selector = 135 }
  case class NthSelector136(p: Int) extends WithIntMember { val selector = 136 }
  case class NthSelector137(p: Int) extends WithIntMember { val selector = 137 }
  case class NthSelector138(p: Int) extends WithIntMember { val selector = 138 }
  case class NthSelector139(p: Int) extends WithIntMember { val selector = 139 }
  case class NthSelector140(p: Int) extends WithIntMember { val selector = 140 }
  case class NthSelector141(p: Int) extends WithIntMember { val selector = 141 }
  case class NthSelector142(p: Int) extends WithIntMember { val selector = 142 }
  case class NthSelector143(p: Int) extends WithIntMember { val selector = 143 }
  case class NthSelector144(p: Int) extends WithIntMember { val selector = 144 }
  case class NthSelector145(p: Int) extends WithIntMember { val selector = 145 }
  case class NthSelector146(p: Int) extends WithIntMember { val selector = 146 }
  case class NthSelector147(p: Int) extends WithIntMember { val selector = 147 }
  case class NthSelector148(p: Int) extends WithIntMember { val selector = 148 }
  case class NthSelector149(p: Int) extends WithIntMember { val selector = 149 }
  case class NthSelector150(p: Int) extends WithIntMember { val selector = 150 }
  case class NthSelector151(p: Int) extends WithIntMember { val selector = 151 }
  case class NthSelector152(p: Int) extends WithIntMember { val selector = 152 }
  case class NthSelector153(p: Int) extends WithIntMember { val selector = 153 }
  case class NthSelector154(p: Int) extends WithIntMember { val selector = 154 }
  case class NthSelector155(p: Int) extends WithIntMember { val selector = 155 }
  case class NthSelector156(p: Int) extends WithIntMember { val selector = 156 }
  case class NthSelector157(p: Int) extends WithIntMember { val selector = 157 }
  case class NthSelector158(p: Int) extends WithIntMember { val selector = 158 }
  case class NthSelector159(p: Int) extends WithIntMember { val selector = 159 }
  case class NthSelector160(p: Int) extends WithIntMember { val selector = 160 }
  case class NthSelector161(p: Int) extends WithIntMember { val selector = 161 }
  case class NthSelector162(p: Int) extends WithIntMember { val selector = 162 }
  case class NthSelector163(p: Int) extends WithIntMember { val selector = 163 }
  case class NthSelector164(p: Int) extends WithIntMember { val selector = 164 }
  case class NthSelector165(p: Int) extends WithIntMember { val selector = 165 }
  case class NthSelector166(p: Int) extends WithIntMember { val selector = 166 }
  case class NthSelector167(p: Int) extends WithIntMember { val selector = 167 }
  case class NthSelector168(p: Int) extends WithIntMember { val selector = 168 }
  case class NthSelector169(p: Int) extends WithIntMember { val selector = 169 }
  case class NthSelector170(p: Int) extends WithIntMember { val selector = 170 }
  case class NthSelector171(p: Int) extends WithIntMember { val selector = 171 }
  case class NthSelector172(p: Int) extends WithIntMember { val selector = 172 }
  case class NthSelector173(p: Int) extends WithIntMember { val selector = 173 }
  case class NthSelector174(p: Int) extends WithIntMember { val selector = 174 }
  case class NthSelector175(p: Int) extends WithIntMember { val selector = 175 }
  case class NthSelector176(p: Int) extends WithIntMember { val selector = 176 }
  case class NthSelector177(p: Int) extends WithIntMember { val selector = 177 }
  case class NthSelector178(p: Int) extends WithIntMember { val selector = 178 }
  case class NthSelector179(p: Int) extends WithIntMember { val selector = 179 }
  case class NthSelector180(p: Int) extends WithIntMember { val selector = 180 }
  case class NthSelector181(p: Int) extends WithIntMember { val selector = 181 }
  case class NthSelector182(p: Int) extends WithIntMember { val selector = 182 }
  case class NthSelector183(p: Int) extends WithIntMember { val selector = 183 }
  case class NthSelector184(p: Int) extends WithIntMember { val selector = 184 }
  case class NthSelector185(p: Int) extends WithIntMember { val selector = 185 }
  case class NthSelector186(p: Int) extends WithIntMember { val selector = 186 }
  case class NthSelector187(p: Int) extends WithIntMember { val selector = 187 }
  case class NthSelector188(p: Int) extends WithIntMember { val selector = 188 }
  case class NthSelector189(p: Int) extends WithIntMember { val selector = 189 }
  case class NthSelector190(p: Int) extends WithIntMember { val selector = 190 }
  case class NthSelector191(p: Int) extends WithIntMember { val selector = 191 }
  case class NthSelector192(p: Int) extends WithIntMember { val selector = 192 }
  case class NthSelector193(p: Int) extends WithIntMember { val selector = 193 }
  case class NthSelector194(p: Int) extends WithIntMember { val selector = 194 }
  case class NthSelector195(p: Int) extends WithIntMember { val selector = 195 }
  case class NthSelector196(p: Int) extends WithIntMember { val selector = 196 }
  case class NthSelector197(p: Int) extends WithIntMember { val selector = 197 }
  case class NthSelector198(p: Int) extends WithIntMember { val selector = 198 }
  case class NthSelector199(p: Int) extends WithIntMember { val selector = 199 }
  case class NthSelector200(p: Int) extends WithIntMember { val selector = 200 }
  case class NthSelector201(p: Int) extends WithIntMember { val selector = 201 }
  case class NthSelector202(p: Int) extends WithIntMember { val selector = 202 }
  case class NthSelector203(p: Int) extends WithIntMember { val selector = 203 }
  case class NthSelector204(p: Int) extends WithIntMember { val selector = 204 }
  case class NthSelector205(p: Int) extends WithIntMember { val selector = 205 }
  case class NthSelector206(p: Int) extends WithIntMember { val selector = 206 }
  case class NthSelector207(p: Int) extends WithIntMember { val selector = 207 }
  case class NthSelector208(p: Int) extends WithIntMember { val selector = 208 }
  case class NthSelector209(p: Int) extends WithIntMember { val selector = 209 }
  case class NthSelector210(p: Int) extends WithIntMember { val selector = 210 }
  case class NthSelector211(p: Int) extends WithIntMember { val selector = 211 }
  case class NthSelector212(p: Int) extends WithIntMember { val selector = 212 }
  case class NthSelector213(p: Int) extends WithIntMember { val selector = 213 }
  case class NthSelector214(p: Int) extends WithIntMember { val selector = 214 }
  case class NthSelector215(p: Int) extends WithIntMember { val selector = 215 }
  case class NthSelector216(p: Int) extends WithIntMember { val selector = 216 }
  case class NthSelector217(p: Int) extends WithIntMember { val selector = 217 }
  case class NthSelector218(p: Int) extends WithIntMember { val selector = 218 }
  case class NthSelector219(p: Int) extends WithIntMember { val selector = 219 }
  case class NthSelector220(p: Int) extends WithIntMember { val selector = 220 }
  case class NthSelector221(p: Int) extends WithIntMember { val selector = 221 }
  case class NthSelector222(p: Int) extends WithIntMember { val selector = 222 }
  case class NthSelector223(p: Int) extends WithIntMember { val selector = 223 }
  case class NthSelector224(p: Int) extends WithIntMember { val selector = 224 }
  case class NthSelector225(p: Int) extends WithIntMember { val selector = 225 }
  case class NthSelector226(p: Int) extends WithIntMember { val selector = 226 }
  case class NthSelector227(p: Int) extends WithIntMember { val selector = 227 }
  case class NthSelector228(p: Int) extends WithIntMember { val selector = 228 }
  case class NthSelector229(p: Int) extends WithIntMember { val selector = 229 }
  case class NthSelector230(p: Int) extends WithIntMember { val selector = 230 }
  case class NthSelector231(p: Int) extends WithIntMember { val selector = 231 }
  case class NthSelector232(p: Int) extends WithIntMember { val selector = 232 }
  case class NthSelector233(p: Int) extends WithIntMember { val selector = 233 }
  case class NthSelector234(p: Int) extends WithIntMember { val selector = 234 }
  case class NthSelector235(p: Int) extends WithIntMember { val selector = 235 }
  case class NthSelector236(p: Int) extends WithIntMember { val selector = 236 }
  case class NthSelector237(p: Int) extends WithIntMember { val selector = 237 }
  case class NthSelector238(p: Int) extends WithIntMember { val selector = 238 }
  case class NthSelector239(p: Int) extends WithIntMember { val selector = 239 }
  case class NthSelector240(p: Int) extends WithIntMember { val selector = 240 }
  case class NthSelector241(p: Int) extends WithIntMember { val selector = 241 }
  case class NthSelector242(p: Int) extends WithIntMember { val selector = 242 }
  case class NthSelector243(p: Int) extends WithIntMember { val selector = 243 }
  case class NthSelector244(p: Int) extends WithIntMember { val selector = 244 }
  case class NthSelector245(p: Int) extends WithIntMember { val selector = 245 }
  case class NthSelector246(p: Int) extends WithIntMember { val selector = 246 }
  case class NthSelector247(p: Int) extends WithIntMember { val selector = 247 }
  case class NthSelector248(p: Int) extends WithIntMember { val selector = 248 }
  case class NthSelector249(p: Int) extends WithIntMember { val selector = 249 }
  case class NthSelector250(p: Int) extends WithIntMember { val selector = 250 }
  case class NthSelector251(p: Int) extends WithIntMember { val selector = 251 }
  case class NthSelector252(p: Int) extends WithIntMember { val selector = 252 }
  case class NthSelector253(p: Int) extends WithIntMember { val selector = 253 }
  case class NthSelector254(p: Int) extends WithIntMember { val selector = 254 }
  case class NthSelector255(p: Int) extends WithIntMember { val selector = 255 }
  case class NthSelector256(p: Int) extends WithIntMember { val selector = 256 }

  @State(Scope.Benchmark)
  class Sorted {
    var s = List.empty[WithIntMember] ++
      (List.empty[WithIntMember].::(NthSelector1(1)).::(NthSelector2(2)).::(NthSelector3(3)).::(NthSelector4(4)).::(NthSelector5(5)).::(NthSelector6(6)).::(NthSelector7(7)).::(NthSelector8(8)).::(NthSelector9(9)).::(NthSelector10(10)).::(NthSelector11(11)).::(NthSelector12(12)).::(NthSelector13(13)).::(NthSelector14(14)).::(NthSelector15(15)).::(NthSelector16(16)).::(NthSelector17(17)).::(NthSelector18(18)).::(NthSelector19(19)).::(NthSelector20(20)).::(NthSelector21(21)).::(NthSelector22(22)).::(NthSelector23(23)).::(NthSelector24(24)).::(NthSelector25(25)).::(NthSelector26(26)).::(NthSelector27(27)).::(NthSelector28(28)).::(NthSelector29(29)).::(NthSelector30(30)).::(NthSelector31(31)).::(NthSelector32(32)).::(NthSelector33(33)).::(NthSelector34(34)).::(NthSelector35(35)).::(NthSelector36(36)).::(NthSelector37(37)).::(NthSelector38(38)).::(NthSelector39(39)).::(NthSelector40(40)).::(NthSelector41(41)).::(NthSelector42(42)).::(NthSelector43(43)).::(NthSelector44(44)).::(NthSelector45(45)).::(NthSelector46(46)).::(NthSelector47(47)).::(NthSelector48(48)).::(NthSelector49(49)).::(NthSelector50(50)).::(NthSelector51(51)).::(NthSelector52(52)).::(NthSelector53(53)).::(NthSelector54(54)).::(NthSelector55(55)).::(NthSelector56(56)).::(NthSelector57(57)).::(NthSelector58(58)).::(NthSelector59(59)).::(NthSelector60(60)).::(NthSelector61(61)).::(NthSelector62(62)).::(NthSelector63(63)).::(NthSelector64(64))) ++
      (List.empty[WithIntMember].::(NthSelector65(65)).::(NthSelector66(66)).::(NthSelector67(67)).::(NthSelector68(68)).::(NthSelector69(69)).::(NthSelector70(70)).::(NthSelector71(71)).::(NthSelector72(72)).::(NthSelector73(73)).::(NthSelector74(74)).::(NthSelector75(75)).::(NthSelector76(76)).::(NthSelector77(77)).::(NthSelector78(78)).::(NthSelector79(79)).::(NthSelector80(80)).::(NthSelector81(81)).::(NthSelector82(82)).::(NthSelector83(83)).::(NthSelector84(84)).::(NthSelector85(85)).::(NthSelector86(86)).::(NthSelector87(87)).::(NthSelector88(88)).::(NthSelector89(89)).::(NthSelector90(90)).::(NthSelector91(91)).::(NthSelector92(92)).::(NthSelector93(93)).::(NthSelector94(94)).::(NthSelector95(95)).::(NthSelector96(96)).::(NthSelector97(97)).::(NthSelector98(98)).::(NthSelector99(99)).::(NthSelector100(100)).::(NthSelector101(101)).::(NthSelector102(102)).::(NthSelector103(103)).::(NthSelector104(104)).::(NthSelector105(105)).::(NthSelector106(106)).::(NthSelector107(107)).::(NthSelector108(108)).::(NthSelector109(109)).::(NthSelector110(110)).::(NthSelector111(111)).::(NthSelector112(112)).::(NthSelector113(113)).::(NthSelector114(114)).::(NthSelector115(115)).::(NthSelector116(116)).::(NthSelector117(117)).::(NthSelector118(118)).::(NthSelector119(119)).::(NthSelector120(120)).::(NthSelector121(121)).::(NthSelector122(122)).::(NthSelector123(123)).::(NthSelector124(124)).::(NthSelector125(125)).::(NthSelector126(126)).::(NthSelector127(127)).::(NthSelector128(128))) ++
      (List.empty[WithIntMember].::(NthSelector129(129)).::(NthSelector130(130)).::(NthSelector131(131)).::(NthSelector132(132)).::(NthSelector133(133)).::(NthSelector134(134)).::(NthSelector135(135)).::(NthSelector136(136)).::(NthSelector137(137)).::(NthSelector138(138)).::(NthSelector139(139)).::(NthSelector140(140)).::(NthSelector141(141)).::(NthSelector142(142)).::(NthSelector143(143)).::(NthSelector144(144)).::(NthSelector145(145)).::(NthSelector146(146)).::(NthSelector147(147)).::(NthSelector148(148)).::(NthSelector149(149)).::(NthSelector150(150)).::(NthSelector151(151)).::(NthSelector152(152)).::(NthSelector153(153)).::(NthSelector154(154)).::(NthSelector155(155)).::(NthSelector156(156)).::(NthSelector157(157)).::(NthSelector158(158)).::(NthSelector159(159)).::(NthSelector160(160)).::(NthSelector161(161)).::(NthSelector162(162)).::(NthSelector163(163)).::(NthSelector164(164)).::(NthSelector165(165)).::(NthSelector166(166)).::(NthSelector167(167)).::(NthSelector168(168)).::(NthSelector169(169)).::(NthSelector170(170)).::(NthSelector171(171)).::(NthSelector172(172)).::(NthSelector173(173)).::(NthSelector174(174)).::(NthSelector175(175)).::(NthSelector176(176)).::(NthSelector177(177)).::(NthSelector178(178)).::(NthSelector179(179)).::(NthSelector180(180)).::(NthSelector181(181)).::(NthSelector182(182)).::(NthSelector183(183)).::(NthSelector184(184)).::(NthSelector185(185)).::(NthSelector186(186)).::(NthSelector187(187)).::(NthSelector188(188)).::(NthSelector189(189)).::(NthSelector190(190)).::(NthSelector191(191)).::(NthSelector192(192))) ++
      (List.empty[WithIntMember].::(NthSelector193(193)).::(NthSelector194(194)).::(NthSelector195(195)).::(NthSelector196(196)).::(NthSelector197(197)).::(NthSelector198(198)).::(NthSelector199(199)).::(NthSelector200(200)).::(NthSelector201(201)).::(NthSelector202(202)).::(NthSelector203(203)).::(NthSelector204(204)).::(NthSelector205(205)).::(NthSelector206(206)).::(NthSelector207(207)).::(NthSelector208(208)).::(NthSelector209(209)).::(NthSelector210(210)).::(NthSelector211(211)).::(NthSelector212(212)).::(NthSelector213(213)).::(NthSelector214(214)).::(NthSelector215(215)).::(NthSelector216(216)).::(NthSelector217(217)).::(NthSelector218(218)).::(NthSelector219(219)).::(NthSelector220(220)).::(NthSelector221(221)).::(NthSelector222(222)).::(NthSelector223(223)).::(NthSelector224(224)).::(NthSelector225(225)).::(NthSelector226(226)).::(NthSelector227(227)).::(NthSelector228(228)).::(NthSelector229(229)).::(NthSelector230(230)).::(NthSelector231(231)).::(NthSelector232(232)).::(NthSelector233(233)).::(NthSelector234(234)).::(NthSelector235(235)).::(NthSelector236(236)).::(NthSelector237(237)).::(NthSelector238(238)).::(NthSelector239(239)).::(NthSelector240(240)).::(NthSelector241(241)).::(NthSelector242(242)).::(NthSelector243(243)).::(NthSelector244(244)).::(NthSelector245(245)).::(NthSelector246(246)).::(NthSelector247(247)).::(NthSelector248(248)).::(NthSelector249(249)).::(NthSelector250(250)).::(NthSelector251(251)).::(NthSelector252(252)).::(NthSelector253(253)).::(NthSelector254(254)).::(NthSelector255(255)).::(NthSelector256(256)))
  }

  @State(Scope.Benchmark)
  class Shuffled {
    var sorted = List.empty[WithIntMember] ++
      (List.empty[WithIntMember].::(NthSelector1(1)).::(NthSelector2(2)).::(NthSelector3(3)).::(NthSelector4(4)).::(NthSelector5(5)).::(NthSelector6(6)).::(NthSelector7(7)).::(NthSelector8(8)).::(NthSelector9(9)).::(NthSelector10(10)).::(NthSelector11(11)).::(NthSelector12(12)).::(NthSelector13(13)).::(NthSelector14(14)).::(NthSelector15(15)).::(NthSelector16(16)).::(NthSelector17(17)).::(NthSelector18(18)).::(NthSelector19(19)).::(NthSelector20(20)).::(NthSelector21(21)).::(NthSelector22(22)).::(NthSelector23(23)).::(NthSelector24(24)).::(NthSelector25(25)).::(NthSelector26(26)).::(NthSelector27(27)).::(NthSelector28(28)).::(NthSelector29(29)).::(NthSelector30(30)).::(NthSelector31(31)).::(NthSelector32(32)).::(NthSelector33(33)).::(NthSelector34(34)).::(NthSelector35(35)).::(NthSelector36(36)).::(NthSelector37(37)).::(NthSelector38(38)).::(NthSelector39(39)).::(NthSelector40(40)).::(NthSelector41(41)).::(NthSelector42(42)).::(NthSelector43(43)).::(NthSelector44(44)).::(NthSelector45(45)).::(NthSelector46(46)).::(NthSelector47(47)).::(NthSelector48(48)).::(NthSelector49(49)).::(NthSelector50(50)).::(NthSelector51(51)).::(NthSelector52(52)).::(NthSelector53(53)).::(NthSelector54(54)).::(NthSelector55(55)).::(NthSelector56(56)).::(NthSelector57(57)).::(NthSelector58(58)).::(NthSelector59(59)).::(NthSelector60(60)).::(NthSelector61(61)).::(NthSelector62(62)).::(NthSelector63(63)).::(NthSelector64(64))) ++
      (List.empty[WithIntMember].::(NthSelector65(65)).::(NthSelector66(66)).::(NthSelector67(67)).::(NthSelector68(68)).::(NthSelector69(69)).::(NthSelector70(70)).::(NthSelector71(71)).::(NthSelector72(72)).::(NthSelector73(73)).::(NthSelector74(74)).::(NthSelector75(75)).::(NthSelector76(76)).::(NthSelector77(77)).::(NthSelector78(78)).::(NthSelector79(79)).::(NthSelector80(80)).::(NthSelector81(81)).::(NthSelector82(82)).::(NthSelector83(83)).::(NthSelector84(84)).::(NthSelector85(85)).::(NthSelector86(86)).::(NthSelector87(87)).::(NthSelector88(88)).::(NthSelector89(89)).::(NthSelector90(90)).::(NthSelector91(91)).::(NthSelector92(92)).::(NthSelector93(93)).::(NthSelector94(94)).::(NthSelector95(95)).::(NthSelector96(96)).::(NthSelector97(97)).::(NthSelector98(98)).::(NthSelector99(99)).::(NthSelector100(100)).::(NthSelector101(101)).::(NthSelector102(102)).::(NthSelector103(103)).::(NthSelector104(104)).::(NthSelector105(105)).::(NthSelector106(106)).::(NthSelector107(107)).::(NthSelector108(108)).::(NthSelector109(109)).::(NthSelector110(110)).::(NthSelector111(111)).::(NthSelector112(112)).::(NthSelector113(113)).::(NthSelector114(114)).::(NthSelector115(115)).::(NthSelector116(116)).::(NthSelector117(117)).::(NthSelector118(118)).::(NthSelector119(119)).::(NthSelector120(120)).::(NthSelector121(121)).::(NthSelector122(122)).::(NthSelector123(123)).::(NthSelector124(124)).::(NthSelector125(125)).::(NthSelector126(126)).::(NthSelector127(127)).::(NthSelector128(128))) ++
      (List.empty[WithIntMember].::(NthSelector129(129)).::(NthSelector130(130)).::(NthSelector131(131)).::(NthSelector132(132)).::(NthSelector133(133)).::(NthSelector134(134)).::(NthSelector135(135)).::(NthSelector136(136)).::(NthSelector137(137)).::(NthSelector138(138)).::(NthSelector139(139)).::(NthSelector140(140)).::(NthSelector141(141)).::(NthSelector142(142)).::(NthSelector143(143)).::(NthSelector144(144)).::(NthSelector145(145)).::(NthSelector146(146)).::(NthSelector147(147)).::(NthSelector148(148)).::(NthSelector149(149)).::(NthSelector150(150)).::(NthSelector151(151)).::(NthSelector152(152)).::(NthSelector153(153)).::(NthSelector154(154)).::(NthSelector155(155)).::(NthSelector156(156)).::(NthSelector157(157)).::(NthSelector158(158)).::(NthSelector159(159)).::(NthSelector160(160)).::(NthSelector161(161)).::(NthSelector162(162)).::(NthSelector163(163)).::(NthSelector164(164)).::(NthSelector165(165)).::(NthSelector166(166)).::(NthSelector167(167)).::(NthSelector168(168)).::(NthSelector169(169)).::(NthSelector170(170)).::(NthSelector171(171)).::(NthSelector172(172)).::(NthSelector173(173)).::(NthSelector174(174)).::(NthSelector175(175)).::(NthSelector176(176)).::(NthSelector177(177)).::(NthSelector178(178)).::(NthSelector179(179)).::(NthSelector180(180)).::(NthSelector181(181)).::(NthSelector182(182)).::(NthSelector183(183)).::(NthSelector184(184)).::(NthSelector185(185)).::(NthSelector186(186)).::(NthSelector187(187)).::(NthSelector188(188)).::(NthSelector189(189)).::(NthSelector190(190)).::(NthSelector191(191)).::(NthSelector192(192))) ++
      (List.empty[WithIntMember].::(NthSelector193(193)).::(NthSelector194(194)).::(NthSelector195(195)).::(NthSelector196(196)).::(NthSelector197(197)).::(NthSelector198(198)).::(NthSelector199(199)).::(NthSelector200(200)).::(NthSelector201(201)).::(NthSelector202(202)).::(NthSelector203(203)).::(NthSelector204(204)).::(NthSelector205(205)).::(NthSelector206(206)).::(NthSelector207(207)).::(NthSelector208(208)).::(NthSelector209(209)).::(NthSelector210(210)).::(NthSelector211(211)).::(NthSelector212(212)).::(NthSelector213(213)).::(NthSelector214(214)).::(NthSelector215(215)).::(NthSelector216(216)).::(NthSelector217(217)).::(NthSelector218(218)).::(NthSelector219(219)).::(NthSelector220(220)).::(NthSelector221(221)).::(NthSelector222(222)).::(NthSelector223(223)).::(NthSelector224(224)).::(NthSelector225(225)).::(NthSelector226(226)).::(NthSelector227(227)).::(NthSelector228(228)).::(NthSelector229(229)).::(NthSelector230(230)).::(NthSelector231(231)).::(NthSelector232(232)).::(NthSelector233(233)).::(NthSelector234(234)).::(NthSelector235(235)).::(NthSelector236(236)).::(NthSelector237(237)).::(NthSelector238(238)).::(NthSelector239(239)).::(NthSelector240(240)).::(NthSelector241(241)).::(NthSelector242(242)).::(NthSelector243(243)).::(NthSelector244(244)).::(NthSelector245(245)).::(NthSelector246(246)).::(NthSelector247(247)).::(NthSelector248(248)).::(NthSelector249(249)).::(NthSelector250(250)).::(NthSelector251(251)).::(NthSelector252(252)).::(NthSelector253(253)).::(NthSelector254(254)).::(NthSelector255(255)).::(NthSelector256(256)))
    var s = new scala.util.Random(256).shuffle(sorted)
  }

}

class IntMemberBenchmark256 {
  import IntMemberData256._
  import scala.annotation._
  import org.openjdk.jmh.infra.Blackhole

  @Benchmark
  @OperationsPerInvocation(256)
  def benchSelectorSorted(bh: Blackhole, state: Sorted) = {

    def selectSelf(caze: WithIntMember) = {
      val sel = caze.selector
      (sel: @switch) match {

        case 1 => bh.consume(caze.asInstanceOf[NthSelector1].p)
        case 2 => bh.consume(caze.asInstanceOf[NthSelector2].p)
        case 3 => bh.consume(caze.asInstanceOf[NthSelector3].p)
        case 4 => bh.consume(caze.asInstanceOf[NthSelector4].p)
        case 5 => bh.consume(caze.asInstanceOf[NthSelector5].p)
        case 6 => bh.consume(caze.asInstanceOf[NthSelector6].p)
        case 7 => bh.consume(caze.asInstanceOf[NthSelector7].p)
        case 8 => bh.consume(caze.asInstanceOf[NthSelector8].p)
        case 9 => bh.consume(caze.asInstanceOf[NthSelector9].p)
        case 10 => bh.consume(caze.asInstanceOf[NthSelector10].p)
        case 11 => bh.consume(caze.asInstanceOf[NthSelector11].p)
        case 12 => bh.consume(caze.asInstanceOf[NthSelector12].p)
        case 13 => bh.consume(caze.asInstanceOf[NthSelector13].p)
        case 14 => bh.consume(caze.asInstanceOf[NthSelector14].p)
        case 15 => bh.consume(caze.asInstanceOf[NthSelector15].p)
        case 16 => bh.consume(caze.asInstanceOf[NthSelector16].p)
        case 17 => bh.consume(caze.asInstanceOf[NthSelector17].p)
        case 18 => bh.consume(caze.asInstanceOf[NthSelector18].p)
        case 19 => bh.consume(caze.asInstanceOf[NthSelector19].p)
        case 20 => bh.consume(caze.asInstanceOf[NthSelector20].p)
        case 21 => bh.consume(caze.asInstanceOf[NthSelector21].p)
        case 22 => bh.consume(caze.asInstanceOf[NthSelector22].p)
        case 23 => bh.consume(caze.asInstanceOf[NthSelector23].p)
        case 24 => bh.consume(caze.asInstanceOf[NthSelector24].p)
        case 25 => bh.consume(caze.asInstanceOf[NthSelector25].p)
        case 26 => bh.consume(caze.asInstanceOf[NthSelector26].p)
        case 27 => bh.consume(caze.asInstanceOf[NthSelector27].p)
        case 28 => bh.consume(caze.asInstanceOf[NthSelector28].p)
        case 29 => bh.consume(caze.asInstanceOf[NthSelector29].p)
        case 30 => bh.consume(caze.asInstanceOf[NthSelector30].p)
        case 31 => bh.consume(caze.asInstanceOf[NthSelector31].p)
        case 32 => bh.consume(caze.asInstanceOf[NthSelector32].p)
        case 33 => bh.consume(caze.asInstanceOf[NthSelector33].p)
        case 34 => bh.consume(caze.asInstanceOf[NthSelector34].p)
        case 35 => bh.consume(caze.asInstanceOf[NthSelector35].p)
        case 36 => bh.consume(caze.asInstanceOf[NthSelector36].p)
        case 37 => bh.consume(caze.asInstanceOf[NthSelector37].p)
        case 38 => bh.consume(caze.asInstanceOf[NthSelector38].p)
        case 39 => bh.consume(caze.asInstanceOf[NthSelector39].p)
        case 40 => bh.consume(caze.asInstanceOf[NthSelector40].p)
        case 41 => bh.consume(caze.asInstanceOf[NthSelector41].p)
        case 42 => bh.consume(caze.asInstanceOf[NthSelector42].p)
        case 43 => bh.consume(caze.asInstanceOf[NthSelector43].p)
        case 44 => bh.consume(caze.asInstanceOf[NthSelector44].p)
        case 45 => bh.consume(caze.asInstanceOf[NthSelector45].p)
        case 46 => bh.consume(caze.asInstanceOf[NthSelector46].p)
        case 47 => bh.consume(caze.asInstanceOf[NthSelector47].p)
        case 48 => bh.consume(caze.asInstanceOf[NthSelector48].p)
        case 49 => bh.consume(caze.asInstanceOf[NthSelector49].p)
        case 50 => bh.consume(caze.asInstanceOf[NthSelector50].p)
        case 51 => bh.consume(caze.asInstanceOf[NthSelector51].p)
        case 52 => bh.consume(caze.asInstanceOf[NthSelector52].p)
        case 53 => bh.consume(caze.asInstanceOf[NthSelector53].p)
        case 54 => bh.consume(caze.asInstanceOf[NthSelector54].p)
        case 55 => bh.consume(caze.asInstanceOf[NthSelector55].p)
        case 56 => bh.consume(caze.asInstanceOf[NthSelector56].p)
        case 57 => bh.consume(caze.asInstanceOf[NthSelector57].p)
        case 58 => bh.consume(caze.asInstanceOf[NthSelector58].p)
        case 59 => bh.consume(caze.asInstanceOf[NthSelector59].p)
        case 60 => bh.consume(caze.asInstanceOf[NthSelector60].p)
        case 61 => bh.consume(caze.asInstanceOf[NthSelector61].p)
        case 62 => bh.consume(caze.asInstanceOf[NthSelector62].p)
        case 63 => bh.consume(caze.asInstanceOf[NthSelector63].p)
        case 64 => bh.consume(caze.asInstanceOf[NthSelector64].p)
        case 65 => bh.consume(caze.asInstanceOf[NthSelector65].p)
        case 66 => bh.consume(caze.asInstanceOf[NthSelector66].p)
        case 67 => bh.consume(caze.asInstanceOf[NthSelector67].p)
        case 68 => bh.consume(caze.asInstanceOf[NthSelector68].p)
        case 69 => bh.consume(caze.asInstanceOf[NthSelector69].p)
        case 70 => bh.consume(caze.asInstanceOf[NthSelector70].p)
        case 71 => bh.consume(caze.asInstanceOf[NthSelector71].p)
        case 72 => bh.consume(caze.asInstanceOf[NthSelector72].p)
        case 73 => bh.consume(caze.asInstanceOf[NthSelector73].p)
        case 74 => bh.consume(caze.asInstanceOf[NthSelector74].p)
        case 75 => bh.consume(caze.asInstanceOf[NthSelector75].p)
        case 76 => bh.consume(caze.asInstanceOf[NthSelector76].p)
        case 77 => bh.consume(caze.asInstanceOf[NthSelector77].p)
        case 78 => bh.consume(caze.asInstanceOf[NthSelector78].p)
        case 79 => bh.consume(caze.asInstanceOf[NthSelector79].p)
        case 80 => bh.consume(caze.asInstanceOf[NthSelector80].p)
        case 81 => bh.consume(caze.asInstanceOf[NthSelector81].p)
        case 82 => bh.consume(caze.asInstanceOf[NthSelector82].p)
        case 83 => bh.consume(caze.asInstanceOf[NthSelector83].p)
        case 84 => bh.consume(caze.asInstanceOf[NthSelector84].p)
        case 85 => bh.consume(caze.asInstanceOf[NthSelector85].p)
        case 86 => bh.consume(caze.asInstanceOf[NthSelector86].p)
        case 87 => bh.consume(caze.asInstanceOf[NthSelector87].p)
        case 88 => bh.consume(caze.asInstanceOf[NthSelector88].p)
        case 89 => bh.consume(caze.asInstanceOf[NthSelector89].p)
        case 90 => bh.consume(caze.asInstanceOf[NthSelector90].p)
        case 91 => bh.consume(caze.asInstanceOf[NthSelector91].p)
        case 92 => bh.consume(caze.asInstanceOf[NthSelector92].p)
        case 93 => bh.consume(caze.asInstanceOf[NthSelector93].p)
        case 94 => bh.consume(caze.asInstanceOf[NthSelector94].p)
        case 95 => bh.consume(caze.asInstanceOf[NthSelector95].p)
        case 96 => bh.consume(caze.asInstanceOf[NthSelector96].p)
        case 97 => bh.consume(caze.asInstanceOf[NthSelector97].p)
        case 98 => bh.consume(caze.asInstanceOf[NthSelector98].p)
        case 99 => bh.consume(caze.asInstanceOf[NthSelector99].p)
        case 100 => bh.consume(caze.asInstanceOf[NthSelector100].p)
        case 101 => bh.consume(caze.asInstanceOf[NthSelector101].p)
        case 102 => bh.consume(caze.asInstanceOf[NthSelector102].p)
        case 103 => bh.consume(caze.asInstanceOf[NthSelector103].p)
        case 104 => bh.consume(caze.asInstanceOf[NthSelector104].p)
        case 105 => bh.consume(caze.asInstanceOf[NthSelector105].p)
        case 106 => bh.consume(caze.asInstanceOf[NthSelector106].p)
        case 107 => bh.consume(caze.asInstanceOf[NthSelector107].p)
        case 108 => bh.consume(caze.asInstanceOf[NthSelector108].p)
        case 109 => bh.consume(caze.asInstanceOf[NthSelector109].p)
        case 110 => bh.consume(caze.asInstanceOf[NthSelector110].p)
        case 111 => bh.consume(caze.asInstanceOf[NthSelector111].p)
        case 112 => bh.consume(caze.asInstanceOf[NthSelector112].p)
        case 113 => bh.consume(caze.asInstanceOf[NthSelector113].p)
        case 114 => bh.consume(caze.asInstanceOf[NthSelector114].p)
        case 115 => bh.consume(caze.asInstanceOf[NthSelector115].p)
        case 116 => bh.consume(caze.asInstanceOf[NthSelector116].p)
        case 117 => bh.consume(caze.asInstanceOf[NthSelector117].p)
        case 118 => bh.consume(caze.asInstanceOf[NthSelector118].p)
        case 119 => bh.consume(caze.asInstanceOf[NthSelector119].p)
        case 120 => bh.consume(caze.asInstanceOf[NthSelector120].p)
        case 121 => bh.consume(caze.asInstanceOf[NthSelector121].p)
        case 122 => bh.consume(caze.asInstanceOf[NthSelector122].p)
        case 123 => bh.consume(caze.asInstanceOf[NthSelector123].p)
        case 124 => bh.consume(caze.asInstanceOf[NthSelector124].p)
        case 125 => bh.consume(caze.asInstanceOf[NthSelector125].p)
        case 126 => bh.consume(caze.asInstanceOf[NthSelector126].p)
        case 127 => bh.consume(caze.asInstanceOf[NthSelector127].p)
        case 128 => bh.consume(caze.asInstanceOf[NthSelector128].p)
        case 129 => bh.consume(caze.asInstanceOf[NthSelector129].p)
        case 130 => bh.consume(caze.asInstanceOf[NthSelector130].p)
        case 131 => bh.consume(caze.asInstanceOf[NthSelector131].p)
        case 132 => bh.consume(caze.asInstanceOf[NthSelector132].p)
        case 133 => bh.consume(caze.asInstanceOf[NthSelector133].p)
        case 134 => bh.consume(caze.asInstanceOf[NthSelector134].p)
        case 135 => bh.consume(caze.asInstanceOf[NthSelector135].p)
        case 136 => bh.consume(caze.asInstanceOf[NthSelector136].p)
        case 137 => bh.consume(caze.asInstanceOf[NthSelector137].p)
        case 138 => bh.consume(caze.asInstanceOf[NthSelector138].p)
        case 139 => bh.consume(caze.asInstanceOf[NthSelector139].p)
        case 140 => bh.consume(caze.asInstanceOf[NthSelector140].p)
        case 141 => bh.consume(caze.asInstanceOf[NthSelector141].p)
        case 142 => bh.consume(caze.asInstanceOf[NthSelector142].p)
        case 143 => bh.consume(caze.asInstanceOf[NthSelector143].p)
        case 144 => bh.consume(caze.asInstanceOf[NthSelector144].p)
        case 145 => bh.consume(caze.asInstanceOf[NthSelector145].p)
        case 146 => bh.consume(caze.asInstanceOf[NthSelector146].p)
        case 147 => bh.consume(caze.asInstanceOf[NthSelector147].p)
        case 148 => bh.consume(caze.asInstanceOf[NthSelector148].p)
        case 149 => bh.consume(caze.asInstanceOf[NthSelector149].p)
        case 150 => bh.consume(caze.asInstanceOf[NthSelector150].p)
        case 151 => bh.consume(caze.asInstanceOf[NthSelector151].p)
        case 152 => bh.consume(caze.asInstanceOf[NthSelector152].p)
        case 153 => bh.consume(caze.asInstanceOf[NthSelector153].p)
        case 154 => bh.consume(caze.asInstanceOf[NthSelector154].p)
        case 155 => bh.consume(caze.asInstanceOf[NthSelector155].p)
        case 156 => bh.consume(caze.asInstanceOf[NthSelector156].p)
        case 157 => bh.consume(caze.asInstanceOf[NthSelector157].p)
        case 158 => bh.consume(caze.asInstanceOf[NthSelector158].p)
        case 159 => bh.consume(caze.asInstanceOf[NthSelector159].p)
        case 160 => bh.consume(caze.asInstanceOf[NthSelector160].p)
        case 161 => bh.consume(caze.asInstanceOf[NthSelector161].p)
        case 162 => bh.consume(caze.asInstanceOf[NthSelector162].p)
        case 163 => bh.consume(caze.asInstanceOf[NthSelector163].p)
        case 164 => bh.consume(caze.asInstanceOf[NthSelector164].p)
        case 165 => bh.consume(caze.asInstanceOf[NthSelector165].p)
        case 166 => bh.consume(caze.asInstanceOf[NthSelector166].p)
        case 167 => bh.consume(caze.asInstanceOf[NthSelector167].p)
        case 168 => bh.consume(caze.asInstanceOf[NthSelector168].p)
        case 169 => bh.consume(caze.asInstanceOf[NthSelector169].p)
        case 170 => bh.consume(caze.asInstanceOf[NthSelector170].p)
        case 171 => bh.consume(caze.asInstanceOf[NthSelector171].p)
        case 172 => bh.consume(caze.asInstanceOf[NthSelector172].p)
        case 173 => bh.consume(caze.asInstanceOf[NthSelector173].p)
        case 174 => bh.consume(caze.asInstanceOf[NthSelector174].p)
        case 175 => bh.consume(caze.asInstanceOf[NthSelector175].p)
        case 176 => bh.consume(caze.asInstanceOf[NthSelector176].p)
        case 177 => bh.consume(caze.asInstanceOf[NthSelector177].p)
        case 178 => bh.consume(caze.asInstanceOf[NthSelector178].p)
        case 179 => bh.consume(caze.asInstanceOf[NthSelector179].p)
        case 180 => bh.consume(caze.asInstanceOf[NthSelector180].p)
        case 181 => bh.consume(caze.asInstanceOf[NthSelector181].p)
        case 182 => bh.consume(caze.asInstanceOf[NthSelector182].p)
        case 183 => bh.consume(caze.asInstanceOf[NthSelector183].p)
        case 184 => bh.consume(caze.asInstanceOf[NthSelector184].p)
        case 185 => bh.consume(caze.asInstanceOf[NthSelector185].p)
        case 186 => bh.consume(caze.asInstanceOf[NthSelector186].p)
        case 187 => bh.consume(caze.asInstanceOf[NthSelector187].p)
        case 188 => bh.consume(caze.asInstanceOf[NthSelector188].p)
        case 189 => bh.consume(caze.asInstanceOf[NthSelector189].p)
        case 190 => bh.consume(caze.asInstanceOf[NthSelector190].p)
        case 191 => bh.consume(caze.asInstanceOf[NthSelector191].p)
        case 192 => bh.consume(caze.asInstanceOf[NthSelector192].p)
        case 193 => bh.consume(caze.asInstanceOf[NthSelector193].p)
        case 194 => bh.consume(caze.asInstanceOf[NthSelector194].p)
        case 195 => bh.consume(caze.asInstanceOf[NthSelector195].p)
        case 196 => bh.consume(caze.asInstanceOf[NthSelector196].p)
        case 197 => bh.consume(caze.asInstanceOf[NthSelector197].p)
        case 198 => bh.consume(caze.asInstanceOf[NthSelector198].p)
        case 199 => bh.consume(caze.asInstanceOf[NthSelector199].p)
        case 200 => bh.consume(caze.asInstanceOf[NthSelector200].p)
        case 201 => bh.consume(caze.asInstanceOf[NthSelector201].p)
        case 202 => bh.consume(caze.asInstanceOf[NthSelector202].p)
        case 203 => bh.consume(caze.asInstanceOf[NthSelector203].p)
        case 204 => bh.consume(caze.asInstanceOf[NthSelector204].p)
        case 205 => bh.consume(caze.asInstanceOf[NthSelector205].p)
        case 206 => bh.consume(caze.asInstanceOf[NthSelector206].p)
        case 207 => bh.consume(caze.asInstanceOf[NthSelector207].p)
        case 208 => bh.consume(caze.asInstanceOf[NthSelector208].p)
        case 209 => bh.consume(caze.asInstanceOf[NthSelector209].p)
        case 210 => bh.consume(caze.asInstanceOf[NthSelector210].p)
        case 211 => bh.consume(caze.asInstanceOf[NthSelector211].p)
        case 212 => bh.consume(caze.asInstanceOf[NthSelector212].p)
        case 213 => bh.consume(caze.asInstanceOf[NthSelector213].p)
        case 214 => bh.consume(caze.asInstanceOf[NthSelector214].p)
        case 215 => bh.consume(caze.asInstanceOf[NthSelector215].p)
        case 216 => bh.consume(caze.asInstanceOf[NthSelector216].p)
        case 217 => bh.consume(caze.asInstanceOf[NthSelector217].p)
        case 218 => bh.consume(caze.asInstanceOf[NthSelector218].p)
        case 219 => bh.consume(caze.asInstanceOf[NthSelector219].p)
        case 220 => bh.consume(caze.asInstanceOf[NthSelector220].p)
        case 221 => bh.consume(caze.asInstanceOf[NthSelector221].p)
        case 222 => bh.consume(caze.asInstanceOf[NthSelector222].p)
        case 223 => bh.consume(caze.asInstanceOf[NthSelector223].p)
        case 224 => bh.consume(caze.asInstanceOf[NthSelector224].p)
        case 225 => bh.consume(caze.asInstanceOf[NthSelector225].p)
        case 226 => bh.consume(caze.asInstanceOf[NthSelector226].p)
        case 227 => bh.consume(caze.asInstanceOf[NthSelector227].p)
        case 228 => bh.consume(caze.asInstanceOf[NthSelector228].p)
        case 229 => bh.consume(caze.asInstanceOf[NthSelector229].p)
        case 230 => bh.consume(caze.asInstanceOf[NthSelector230].p)
        case 231 => bh.consume(caze.asInstanceOf[NthSelector231].p)
        case 232 => bh.consume(caze.asInstanceOf[NthSelector232].p)
        case 233 => bh.consume(caze.asInstanceOf[NthSelector233].p)
        case 234 => bh.consume(caze.asInstanceOf[NthSelector234].p)
        case 235 => bh.consume(caze.asInstanceOf[NthSelector235].p)
        case 236 => bh.consume(caze.asInstanceOf[NthSelector236].p)
        case 237 => bh.consume(caze.asInstanceOf[NthSelector237].p)
        case 238 => bh.consume(caze.asInstanceOf[NthSelector238].p)
        case 239 => bh.consume(caze.asInstanceOf[NthSelector239].p)
        case 240 => bh.consume(caze.asInstanceOf[NthSelector240].p)
        case 241 => bh.consume(caze.asInstanceOf[NthSelector241].p)
        case 242 => bh.consume(caze.asInstanceOf[NthSelector242].p)
        case 243 => bh.consume(caze.asInstanceOf[NthSelector243].p)
        case 244 => bh.consume(caze.asInstanceOf[NthSelector244].p)
        case 245 => bh.consume(caze.asInstanceOf[NthSelector245].p)
        case 246 => bh.consume(caze.asInstanceOf[NthSelector246].p)
        case 247 => bh.consume(caze.asInstanceOf[NthSelector247].p)
        case 248 => bh.consume(caze.asInstanceOf[NthSelector248].p)
        case 249 => bh.consume(caze.asInstanceOf[NthSelector249].p)
        case 250 => bh.consume(caze.asInstanceOf[NthSelector250].p)
        case 251 => bh.consume(caze.asInstanceOf[NthSelector251].p)
        case 252 => bh.consume(caze.asInstanceOf[NthSelector252].p)
        case 253 => bh.consume(caze.asInstanceOf[NthSelector253].p)
        case 254 => bh.consume(caze.asInstanceOf[NthSelector254].p)
        case 255 => bh.consume(caze.asInstanceOf[NthSelector255].p)
        case 256 => bh.consume(caze.asInstanceOf[NthSelector256].p)
      }
    }

    state.s.foreach(selectSelf)

  }

  @Benchmark
  @OperationsPerInvocation(256)
  def benchSelectorUnsorted(bh: Blackhole, state: Shuffled) = {

    def selectSelf(caze: WithIntMember) = {
      val sel = caze.selector
      (sel: @switch) match {

        case 1 => bh.consume(caze.asInstanceOf[NthSelector1].p)
        case 2 => bh.consume(caze.asInstanceOf[NthSelector2].p)
        case 3 => bh.consume(caze.asInstanceOf[NthSelector3].p)
        case 4 => bh.consume(caze.asInstanceOf[NthSelector4].p)
        case 5 => bh.consume(caze.asInstanceOf[NthSelector5].p)
        case 6 => bh.consume(caze.asInstanceOf[NthSelector6].p)
        case 7 => bh.consume(caze.asInstanceOf[NthSelector7].p)
        case 8 => bh.consume(caze.asInstanceOf[NthSelector8].p)
        case 9 => bh.consume(caze.asInstanceOf[NthSelector9].p)
        case 10 => bh.consume(caze.asInstanceOf[NthSelector10].p)
        case 11 => bh.consume(caze.asInstanceOf[NthSelector11].p)
        case 12 => bh.consume(caze.asInstanceOf[NthSelector12].p)
        case 13 => bh.consume(caze.asInstanceOf[NthSelector13].p)
        case 14 => bh.consume(caze.asInstanceOf[NthSelector14].p)
        case 15 => bh.consume(caze.asInstanceOf[NthSelector15].p)
        case 16 => bh.consume(caze.asInstanceOf[NthSelector16].p)
        case 17 => bh.consume(caze.asInstanceOf[NthSelector17].p)
        case 18 => bh.consume(caze.asInstanceOf[NthSelector18].p)
        case 19 => bh.consume(caze.asInstanceOf[NthSelector19].p)
        case 20 => bh.consume(caze.asInstanceOf[NthSelector20].p)
        case 21 => bh.consume(caze.asInstanceOf[NthSelector21].p)
        case 22 => bh.consume(caze.asInstanceOf[NthSelector22].p)
        case 23 => bh.consume(caze.asInstanceOf[NthSelector23].p)
        case 24 => bh.consume(caze.asInstanceOf[NthSelector24].p)
        case 25 => bh.consume(caze.asInstanceOf[NthSelector25].p)
        case 26 => bh.consume(caze.asInstanceOf[NthSelector26].p)
        case 27 => bh.consume(caze.asInstanceOf[NthSelector27].p)
        case 28 => bh.consume(caze.asInstanceOf[NthSelector28].p)
        case 29 => bh.consume(caze.asInstanceOf[NthSelector29].p)
        case 30 => bh.consume(caze.asInstanceOf[NthSelector30].p)
        case 31 => bh.consume(caze.asInstanceOf[NthSelector31].p)
        case 32 => bh.consume(caze.asInstanceOf[NthSelector32].p)
        case 33 => bh.consume(caze.asInstanceOf[NthSelector33].p)
        case 34 => bh.consume(caze.asInstanceOf[NthSelector34].p)
        case 35 => bh.consume(caze.asInstanceOf[NthSelector35].p)
        case 36 => bh.consume(caze.asInstanceOf[NthSelector36].p)
        case 37 => bh.consume(caze.asInstanceOf[NthSelector37].p)
        case 38 => bh.consume(caze.asInstanceOf[NthSelector38].p)
        case 39 => bh.consume(caze.asInstanceOf[NthSelector39].p)
        case 40 => bh.consume(caze.asInstanceOf[NthSelector40].p)
        case 41 => bh.consume(caze.asInstanceOf[NthSelector41].p)
        case 42 => bh.consume(caze.asInstanceOf[NthSelector42].p)
        case 43 => bh.consume(caze.asInstanceOf[NthSelector43].p)
        case 44 => bh.consume(caze.asInstanceOf[NthSelector44].p)
        case 45 => bh.consume(caze.asInstanceOf[NthSelector45].p)
        case 46 => bh.consume(caze.asInstanceOf[NthSelector46].p)
        case 47 => bh.consume(caze.asInstanceOf[NthSelector47].p)
        case 48 => bh.consume(caze.asInstanceOf[NthSelector48].p)
        case 49 => bh.consume(caze.asInstanceOf[NthSelector49].p)
        case 50 => bh.consume(caze.asInstanceOf[NthSelector50].p)
        case 51 => bh.consume(caze.asInstanceOf[NthSelector51].p)
        case 52 => bh.consume(caze.asInstanceOf[NthSelector52].p)
        case 53 => bh.consume(caze.asInstanceOf[NthSelector53].p)
        case 54 => bh.consume(caze.asInstanceOf[NthSelector54].p)
        case 55 => bh.consume(caze.asInstanceOf[NthSelector55].p)
        case 56 => bh.consume(caze.asInstanceOf[NthSelector56].p)
        case 57 => bh.consume(caze.asInstanceOf[NthSelector57].p)
        case 58 => bh.consume(caze.asInstanceOf[NthSelector58].p)
        case 59 => bh.consume(caze.asInstanceOf[NthSelector59].p)
        case 60 => bh.consume(caze.asInstanceOf[NthSelector60].p)
        case 61 => bh.consume(caze.asInstanceOf[NthSelector61].p)
        case 62 => bh.consume(caze.asInstanceOf[NthSelector62].p)
        case 63 => bh.consume(caze.asInstanceOf[NthSelector63].p)
        case 64 => bh.consume(caze.asInstanceOf[NthSelector64].p)
        case 65 => bh.consume(caze.asInstanceOf[NthSelector65].p)
        case 66 => bh.consume(caze.asInstanceOf[NthSelector66].p)
        case 67 => bh.consume(caze.asInstanceOf[NthSelector67].p)
        case 68 => bh.consume(caze.asInstanceOf[NthSelector68].p)
        case 69 => bh.consume(caze.asInstanceOf[NthSelector69].p)
        case 70 => bh.consume(caze.asInstanceOf[NthSelector70].p)
        case 71 => bh.consume(caze.asInstanceOf[NthSelector71].p)
        case 72 => bh.consume(caze.asInstanceOf[NthSelector72].p)
        case 73 => bh.consume(caze.asInstanceOf[NthSelector73].p)
        case 74 => bh.consume(caze.asInstanceOf[NthSelector74].p)
        case 75 => bh.consume(caze.asInstanceOf[NthSelector75].p)
        case 76 => bh.consume(caze.asInstanceOf[NthSelector76].p)
        case 77 => bh.consume(caze.asInstanceOf[NthSelector77].p)
        case 78 => bh.consume(caze.asInstanceOf[NthSelector78].p)
        case 79 => bh.consume(caze.asInstanceOf[NthSelector79].p)
        case 80 => bh.consume(caze.asInstanceOf[NthSelector80].p)
        case 81 => bh.consume(caze.asInstanceOf[NthSelector81].p)
        case 82 => bh.consume(caze.asInstanceOf[NthSelector82].p)
        case 83 => bh.consume(caze.asInstanceOf[NthSelector83].p)
        case 84 => bh.consume(caze.asInstanceOf[NthSelector84].p)
        case 85 => bh.consume(caze.asInstanceOf[NthSelector85].p)
        case 86 => bh.consume(caze.asInstanceOf[NthSelector86].p)
        case 87 => bh.consume(caze.asInstanceOf[NthSelector87].p)
        case 88 => bh.consume(caze.asInstanceOf[NthSelector88].p)
        case 89 => bh.consume(caze.asInstanceOf[NthSelector89].p)
        case 90 => bh.consume(caze.asInstanceOf[NthSelector90].p)
        case 91 => bh.consume(caze.asInstanceOf[NthSelector91].p)
        case 92 => bh.consume(caze.asInstanceOf[NthSelector92].p)
        case 93 => bh.consume(caze.asInstanceOf[NthSelector93].p)
        case 94 => bh.consume(caze.asInstanceOf[NthSelector94].p)
        case 95 => bh.consume(caze.asInstanceOf[NthSelector95].p)
        case 96 => bh.consume(caze.asInstanceOf[NthSelector96].p)
        case 97 => bh.consume(caze.asInstanceOf[NthSelector97].p)
        case 98 => bh.consume(caze.asInstanceOf[NthSelector98].p)
        case 99 => bh.consume(caze.asInstanceOf[NthSelector99].p)
        case 100 => bh.consume(caze.asInstanceOf[NthSelector100].p)
        case 101 => bh.consume(caze.asInstanceOf[NthSelector101].p)
        case 102 => bh.consume(caze.asInstanceOf[NthSelector102].p)
        case 103 => bh.consume(caze.asInstanceOf[NthSelector103].p)
        case 104 => bh.consume(caze.asInstanceOf[NthSelector104].p)
        case 105 => bh.consume(caze.asInstanceOf[NthSelector105].p)
        case 106 => bh.consume(caze.asInstanceOf[NthSelector106].p)
        case 107 => bh.consume(caze.asInstanceOf[NthSelector107].p)
        case 108 => bh.consume(caze.asInstanceOf[NthSelector108].p)
        case 109 => bh.consume(caze.asInstanceOf[NthSelector109].p)
        case 110 => bh.consume(caze.asInstanceOf[NthSelector110].p)
        case 111 => bh.consume(caze.asInstanceOf[NthSelector111].p)
        case 112 => bh.consume(caze.asInstanceOf[NthSelector112].p)
        case 113 => bh.consume(caze.asInstanceOf[NthSelector113].p)
        case 114 => bh.consume(caze.asInstanceOf[NthSelector114].p)
        case 115 => bh.consume(caze.asInstanceOf[NthSelector115].p)
        case 116 => bh.consume(caze.asInstanceOf[NthSelector116].p)
        case 117 => bh.consume(caze.asInstanceOf[NthSelector117].p)
        case 118 => bh.consume(caze.asInstanceOf[NthSelector118].p)
        case 119 => bh.consume(caze.asInstanceOf[NthSelector119].p)
        case 120 => bh.consume(caze.asInstanceOf[NthSelector120].p)
        case 121 => bh.consume(caze.asInstanceOf[NthSelector121].p)
        case 122 => bh.consume(caze.asInstanceOf[NthSelector122].p)
        case 123 => bh.consume(caze.asInstanceOf[NthSelector123].p)
        case 124 => bh.consume(caze.asInstanceOf[NthSelector124].p)
        case 125 => bh.consume(caze.asInstanceOf[NthSelector125].p)
        case 126 => bh.consume(caze.asInstanceOf[NthSelector126].p)
        case 127 => bh.consume(caze.asInstanceOf[NthSelector127].p)
        case 128 => bh.consume(caze.asInstanceOf[NthSelector128].p)
        case 129 => bh.consume(caze.asInstanceOf[NthSelector129].p)
        case 130 => bh.consume(caze.asInstanceOf[NthSelector130].p)
        case 131 => bh.consume(caze.asInstanceOf[NthSelector131].p)
        case 132 => bh.consume(caze.asInstanceOf[NthSelector132].p)
        case 133 => bh.consume(caze.asInstanceOf[NthSelector133].p)
        case 134 => bh.consume(caze.asInstanceOf[NthSelector134].p)
        case 135 => bh.consume(caze.asInstanceOf[NthSelector135].p)
        case 136 => bh.consume(caze.asInstanceOf[NthSelector136].p)
        case 137 => bh.consume(caze.asInstanceOf[NthSelector137].p)
        case 138 => bh.consume(caze.asInstanceOf[NthSelector138].p)
        case 139 => bh.consume(caze.asInstanceOf[NthSelector139].p)
        case 140 => bh.consume(caze.asInstanceOf[NthSelector140].p)
        case 141 => bh.consume(caze.asInstanceOf[NthSelector141].p)
        case 142 => bh.consume(caze.asInstanceOf[NthSelector142].p)
        case 143 => bh.consume(caze.asInstanceOf[NthSelector143].p)
        case 144 => bh.consume(caze.asInstanceOf[NthSelector144].p)
        case 145 => bh.consume(caze.asInstanceOf[NthSelector145].p)
        case 146 => bh.consume(caze.asInstanceOf[NthSelector146].p)
        case 147 => bh.consume(caze.asInstanceOf[NthSelector147].p)
        case 148 => bh.consume(caze.asInstanceOf[NthSelector148].p)
        case 149 => bh.consume(caze.asInstanceOf[NthSelector149].p)
        case 150 => bh.consume(caze.asInstanceOf[NthSelector150].p)
        case 151 => bh.consume(caze.asInstanceOf[NthSelector151].p)
        case 152 => bh.consume(caze.asInstanceOf[NthSelector152].p)
        case 153 => bh.consume(caze.asInstanceOf[NthSelector153].p)
        case 154 => bh.consume(caze.asInstanceOf[NthSelector154].p)
        case 155 => bh.consume(caze.asInstanceOf[NthSelector155].p)
        case 156 => bh.consume(caze.asInstanceOf[NthSelector156].p)
        case 157 => bh.consume(caze.asInstanceOf[NthSelector157].p)
        case 158 => bh.consume(caze.asInstanceOf[NthSelector158].p)
        case 159 => bh.consume(caze.asInstanceOf[NthSelector159].p)
        case 160 => bh.consume(caze.asInstanceOf[NthSelector160].p)
        case 161 => bh.consume(caze.asInstanceOf[NthSelector161].p)
        case 162 => bh.consume(caze.asInstanceOf[NthSelector162].p)
        case 163 => bh.consume(caze.asInstanceOf[NthSelector163].p)
        case 164 => bh.consume(caze.asInstanceOf[NthSelector164].p)
        case 165 => bh.consume(caze.asInstanceOf[NthSelector165].p)
        case 166 => bh.consume(caze.asInstanceOf[NthSelector166].p)
        case 167 => bh.consume(caze.asInstanceOf[NthSelector167].p)
        case 168 => bh.consume(caze.asInstanceOf[NthSelector168].p)
        case 169 => bh.consume(caze.asInstanceOf[NthSelector169].p)
        case 170 => bh.consume(caze.asInstanceOf[NthSelector170].p)
        case 171 => bh.consume(caze.asInstanceOf[NthSelector171].p)
        case 172 => bh.consume(caze.asInstanceOf[NthSelector172].p)
        case 173 => bh.consume(caze.asInstanceOf[NthSelector173].p)
        case 174 => bh.consume(caze.asInstanceOf[NthSelector174].p)
        case 175 => bh.consume(caze.asInstanceOf[NthSelector175].p)
        case 176 => bh.consume(caze.asInstanceOf[NthSelector176].p)
        case 177 => bh.consume(caze.asInstanceOf[NthSelector177].p)
        case 178 => bh.consume(caze.asInstanceOf[NthSelector178].p)
        case 179 => bh.consume(caze.asInstanceOf[NthSelector179].p)
        case 180 => bh.consume(caze.asInstanceOf[NthSelector180].p)
        case 181 => bh.consume(caze.asInstanceOf[NthSelector181].p)
        case 182 => bh.consume(caze.asInstanceOf[NthSelector182].p)
        case 183 => bh.consume(caze.asInstanceOf[NthSelector183].p)
        case 184 => bh.consume(caze.asInstanceOf[NthSelector184].p)
        case 185 => bh.consume(caze.asInstanceOf[NthSelector185].p)
        case 186 => bh.consume(caze.asInstanceOf[NthSelector186].p)
        case 187 => bh.consume(caze.asInstanceOf[NthSelector187].p)
        case 188 => bh.consume(caze.asInstanceOf[NthSelector188].p)
        case 189 => bh.consume(caze.asInstanceOf[NthSelector189].p)
        case 190 => bh.consume(caze.asInstanceOf[NthSelector190].p)
        case 191 => bh.consume(caze.asInstanceOf[NthSelector191].p)
        case 192 => bh.consume(caze.asInstanceOf[NthSelector192].p)
        case 193 => bh.consume(caze.asInstanceOf[NthSelector193].p)
        case 194 => bh.consume(caze.asInstanceOf[NthSelector194].p)
        case 195 => bh.consume(caze.asInstanceOf[NthSelector195].p)
        case 196 => bh.consume(caze.asInstanceOf[NthSelector196].p)
        case 197 => bh.consume(caze.asInstanceOf[NthSelector197].p)
        case 198 => bh.consume(caze.asInstanceOf[NthSelector198].p)
        case 199 => bh.consume(caze.asInstanceOf[NthSelector199].p)
        case 200 => bh.consume(caze.asInstanceOf[NthSelector200].p)
        case 201 => bh.consume(caze.asInstanceOf[NthSelector201].p)
        case 202 => bh.consume(caze.asInstanceOf[NthSelector202].p)
        case 203 => bh.consume(caze.asInstanceOf[NthSelector203].p)
        case 204 => bh.consume(caze.asInstanceOf[NthSelector204].p)
        case 205 => bh.consume(caze.asInstanceOf[NthSelector205].p)
        case 206 => bh.consume(caze.asInstanceOf[NthSelector206].p)
        case 207 => bh.consume(caze.asInstanceOf[NthSelector207].p)
        case 208 => bh.consume(caze.asInstanceOf[NthSelector208].p)
        case 209 => bh.consume(caze.asInstanceOf[NthSelector209].p)
        case 210 => bh.consume(caze.asInstanceOf[NthSelector210].p)
        case 211 => bh.consume(caze.asInstanceOf[NthSelector211].p)
        case 212 => bh.consume(caze.asInstanceOf[NthSelector212].p)
        case 213 => bh.consume(caze.asInstanceOf[NthSelector213].p)
        case 214 => bh.consume(caze.asInstanceOf[NthSelector214].p)
        case 215 => bh.consume(caze.asInstanceOf[NthSelector215].p)
        case 216 => bh.consume(caze.asInstanceOf[NthSelector216].p)
        case 217 => bh.consume(caze.asInstanceOf[NthSelector217].p)
        case 218 => bh.consume(caze.asInstanceOf[NthSelector218].p)
        case 219 => bh.consume(caze.asInstanceOf[NthSelector219].p)
        case 220 => bh.consume(caze.asInstanceOf[NthSelector220].p)
        case 221 => bh.consume(caze.asInstanceOf[NthSelector221].p)
        case 222 => bh.consume(caze.asInstanceOf[NthSelector222].p)
        case 223 => bh.consume(caze.asInstanceOf[NthSelector223].p)
        case 224 => bh.consume(caze.asInstanceOf[NthSelector224].p)
        case 225 => bh.consume(caze.asInstanceOf[NthSelector225].p)
        case 226 => bh.consume(caze.asInstanceOf[NthSelector226].p)
        case 227 => bh.consume(caze.asInstanceOf[NthSelector227].p)
        case 228 => bh.consume(caze.asInstanceOf[NthSelector228].p)
        case 229 => bh.consume(caze.asInstanceOf[NthSelector229].p)
        case 230 => bh.consume(caze.asInstanceOf[NthSelector230].p)
        case 231 => bh.consume(caze.asInstanceOf[NthSelector231].p)
        case 232 => bh.consume(caze.asInstanceOf[NthSelector232].p)
        case 233 => bh.consume(caze.asInstanceOf[NthSelector233].p)
        case 234 => bh.consume(caze.asInstanceOf[NthSelector234].p)
        case 235 => bh.consume(caze.asInstanceOf[NthSelector235].p)
        case 236 => bh.consume(caze.asInstanceOf[NthSelector236].p)
        case 237 => bh.consume(caze.asInstanceOf[NthSelector237].p)
        case 238 => bh.consume(caze.asInstanceOf[NthSelector238].p)
        case 239 => bh.consume(caze.asInstanceOf[NthSelector239].p)
        case 240 => bh.consume(caze.asInstanceOf[NthSelector240].p)
        case 241 => bh.consume(caze.asInstanceOf[NthSelector241].p)
        case 242 => bh.consume(caze.asInstanceOf[NthSelector242].p)
        case 243 => bh.consume(caze.asInstanceOf[NthSelector243].p)
        case 244 => bh.consume(caze.asInstanceOf[NthSelector244].p)
        case 245 => bh.consume(caze.asInstanceOf[NthSelector245].p)
        case 246 => bh.consume(caze.asInstanceOf[NthSelector246].p)
        case 247 => bh.consume(caze.asInstanceOf[NthSelector247].p)
        case 248 => bh.consume(caze.asInstanceOf[NthSelector248].p)
        case 249 => bh.consume(caze.asInstanceOf[NthSelector249].p)
        case 250 => bh.consume(caze.asInstanceOf[NthSelector250].p)
        case 251 => bh.consume(caze.asInstanceOf[NthSelector251].p)
        case 252 => bh.consume(caze.asInstanceOf[NthSelector252].p)
        case 253 => bh.consume(caze.asInstanceOf[NthSelector253].p)
        case 254 => bh.consume(caze.asInstanceOf[NthSelector254].p)
        case 255 => bh.consume(caze.asInstanceOf[NthSelector255].p)
        case 256 => bh.consume(caze.asInstanceOf[NthSelector256].p)
      }
    }

    state.s.foreach(selectSelf)

  }

}